/* tslint:disable */
/* eslint-disable */
/**
 * Arke IAM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DateAttr } from './DateAttr';
import {
    DateAttrFromJSON,
    DateAttrFromJSONTyped,
    DateAttrToJSON,
} from './DateAttr';

/**
 * 
 * @export
 * @interface UserCreate
 */
export interface UserCreate {
    /**
     * 
     * @type {DateAttr}
     * @memberof UserCreate
     */
    created?: DateAttr;
    /**
     * 
     * @type {DateAttr}
     * @memberof UserCreate
     */
    updated?: DateAttr;
    /**
     * 
     * @type {number}
     * @memberof UserCreate
     */
    version: number;
    /**
     * 
     * @type {boolean}
     * @memberof UserCreate
     */
    archived?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    fullName: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    email?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserCreate
     */
    roles: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    password: string;
}

/**
 * Check if a given object implements the UserCreate interface.
 */
export function instanceOfUserCreate(value: object): value is UserCreate {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    if (!('roles' in value) || value['roles'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UserCreateFromJSON(json: any): UserCreate {
    return UserCreateFromJSONTyped(json, false);
}

export function UserCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : DateAttrFromJSON(json['created']),
        'updated': json['updated'] == null ? undefined : DateAttrFromJSON(json['updated']),
        'version': json['version'],
        'archived': json['archived'] == null ? undefined : json['archived'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'],
        'fullName': json['full_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'roles': json['roles'],
        'password': json['password'],
    };
}

export function UserCreateToJSON(value?: UserCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created': DateAttrToJSON(value['created']),
        'updated': DateAttrToJSON(value['updated']),
        'version': value['version'],
        'archived': value['archived'],
        'notes': value['notes'],
        'id': value['id'],
        'username': value['username'],
        'full_name': value['fullName'],
        'email': value['email'],
        'roles': value['roles'],
        'password': value['password'],
    };
}

