/* tslint:disable */
/* eslint-disable */
/**
 * Arke IAM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TenantDetails,
} from '../models/index';
import {
    TenantDetailsFromJSON,
    TenantDetailsToJSON,
} from '../models/index';

export interface UpdateTenantRequest {
    tenantDetails?: TenantDetails;
}

/**
 * 
 */
export class TenantApi extends runtime.BaseAPI {

    /**
     */
    async showTenantRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantDetails>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/tenant`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TenantDetailsFromJSON(jsonValue));
    }

    /**
     */
    async showTenant(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantDetails> {
        const response = await this.showTenantRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async updateTenantRaw(requestParameters: UpdateTenantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantDetails>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/tenant`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TenantDetailsToJSON(requestParameters['tenantDetails']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TenantDetailsFromJSON(jsonValue));
    }

    /**
     */
    async updateTenant(requestParameters: UpdateTenantRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantDetails> {
        const response = await this.updateTenantRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
