/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RawMaterialsInventoryValue,
} from '../models/index';
import {
    RawMaterialsInventoryValueFromJSON,
    RawMaterialsInventoryValueToJSON,
} from '../models/index';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async computeRawMaterialInventoryValueRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RawMaterialsInventoryValue>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/inventory/raw-material/_compute-value`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RawMaterialsInventoryValueFromJSON(jsonValue));
    }

    /**
     */
    async computeRawMaterialInventoryValue(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RawMaterialsInventoryValue> {
        const response = await this.computeRawMaterialInventoryValueRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async listSupplierCategoriesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/supplier/_categories`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async listSupplierCategories(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.listSupplierCategoriesRaw(initOverrides);
        return await response.value();
    }

}
