/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PricesAttr } from './PricesAttr';
import {
    PricesAttrFromJSON,
    PricesAttrFromJSONTyped,
    PricesAttrToJSON,
} from './PricesAttr';

/**
 * 
 * @export
 * @interface PricedQuantifiedItem
 */
export interface PricedQuantifiedItem {
    /**
     * 
     * @type {string}
     * @memberof PricedQuantifiedItem
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PricedQuantifiedItem
     */
    extraId?: string;
    /**
     * 
     * @type {string}
     * @memberof PricedQuantifiedItem
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof PricedQuantifiedItem
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof PricedQuantifiedItem
     */
    uom: string;
    /**
     * 
     * @type {string}
     * @memberof PricedQuantifiedItem
     */
    orderId?: string;
    /**
     * 
     * @type {PricesAttr}
     * @memberof PricedQuantifiedItem
     */
    prices?: PricesAttr;
}

/**
 * Check if a given object implements the PricedQuantifiedItem interface.
 */
export function instanceOfPricedQuantifiedItem(value: object): value is PricedQuantifiedItem {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('uom' in value) || value['uom'] === undefined) return false;
    return true;
}

export function PricedQuantifiedItemFromJSON(json: any): PricedQuantifiedItem {
    return PricedQuantifiedItemFromJSONTyped(json, false);
}

export function PricedQuantifiedItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricedQuantifiedItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'extraId': json['extra_id'] == null ? undefined : json['extra_id'],
        'name': json['name'],
        'quantity': json['quantity'],
        'uom': json['uom'],
        'orderId': json['order_id'] == null ? undefined : json['order_id'],
        'prices': json['prices'] == null ? undefined : PricesAttrFromJSON(json['prices']),
    };
}

export function PricedQuantifiedItemToJSON(value?: PricedQuantifiedItem | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'extra_id': value['extraId'],
        'name': value['name'],
        'quantity': value['quantity'],
        'uom': value['uom'],
        'order_id': value['orderId'],
        'prices': PricesAttrToJSON(value['prices']),
    };
}

