/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RawMaterialSummary } from './RawMaterialSummary';
import {
    RawMaterialSummaryFromJSON,
    RawMaterialSummaryFromJSONTyped,
    RawMaterialSummaryToJSON,
} from './RawMaterialSummary';
import type { DateAttr } from './DateAttr';
import {
    DateAttrFromJSON,
    DateAttrFromJSONTyped,
    DateAttrToJSON,
} from './DateAttr';
import type { PricesAttr } from './PricesAttr';
import {
    PricesAttrFromJSON,
    PricesAttrFromJSONTyped,
    PricesAttrToJSON,
} from './PricesAttr';
import type { CompanyAttr } from './CompanyAttr';
import {
    CompanyAttrFromJSON,
    CompanyAttrFromJSONTyped,
    CompanyAttrToJSON,
} from './CompanyAttr';

/**
 * 
 * @export
 * @interface RawMaterialDetails
 */
export interface RawMaterialDetails {
    /**
     * 
     * @type {DateAttr}
     * @memberof RawMaterialDetails
     */
    created?: DateAttr;
    /**
     * 
     * @type {DateAttr}
     * @memberof RawMaterialDetails
     */
    updated?: DateAttr;
    /**
     * 
     * @type {number}
     * @memberof RawMaterialDetails
     */
    version: number;
    /**
     * 
     * @type {boolean}
     * @memberof RawMaterialDetails
     */
    archived?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialDetails
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialDetails
     */
    supplierId: string;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialDetails
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialDetails
     */
    externalId: string;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialDetails
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialDetails
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RawMaterialDetails
     */
    categories: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialDetails
     */
    uom: string;
    /**
     * 
     * @type {CompanyAttr}
     * @memberof RawMaterialDetails
     */
    supplierAttr?: CompanyAttr;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialDetails
     */
    aggregateOfId?: string;
    /**
     * 
     * @type {RawMaterialSummary}
     * @memberof RawMaterialDetails
     */
    aggregateOf?: RawMaterialSummary;
    /**
     * 
     * @type {number}
     * @memberof RawMaterialDetails
     */
    aggregateQuantity?: number;
    /**
     * 
     * @type {PricesAttr}
     * @memberof RawMaterialDetails
     */
    prices?: PricesAttr;
    /**
     * 
     * @type {number}
     * @memberof RawMaterialDetails
     */
    minimumQuantity: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof RawMaterialDetails
     */
    attributes?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof RawMaterialDetails
     */
    leadTime?: string;
}

/**
 * Check if a given object implements the RawMaterialDetails interface.
 */
export function instanceOfRawMaterialDetails(value: object): value is RawMaterialDetails {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('supplierId' in value) || value['supplierId'] === undefined) return false;
    if (!('externalId' in value) || value['externalId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    if (!('uom' in value) || value['uom'] === undefined) return false;
    if (!('minimumQuantity' in value) || value['minimumQuantity'] === undefined) return false;
    return true;
}

export function RawMaterialDetailsFromJSON(json: any): RawMaterialDetails {
    return RawMaterialDetailsFromJSONTyped(json, false);
}

export function RawMaterialDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RawMaterialDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : DateAttrFromJSON(json['created']),
        'updated': json['updated'] == null ? undefined : DateAttrFromJSON(json['updated']),
        'version': json['version'],
        'archived': json['archived'] == null ? undefined : json['archived'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'supplierId': json['supplier_id'],
        'id': json['id'] == null ? undefined : json['id'],
        'externalId': json['external_id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'categories': json['categories'],
        'uom': json['uom'],
        'supplierAttr': json['supplier_attr'] == null ? undefined : CompanyAttrFromJSON(json['supplier_attr']),
        'aggregateOfId': json['aggregate_of_id'] == null ? undefined : json['aggregate_of_id'],
        'aggregateOf': json['aggregate_of'] == null ? undefined : RawMaterialSummaryFromJSON(json['aggregate_of']),
        'aggregateQuantity': json['aggregate_quantity'] == null ? undefined : json['aggregate_quantity'],
        'prices': json['prices'] == null ? undefined : PricesAttrFromJSON(json['prices']),
        'minimumQuantity': json['minimum_quantity'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'leadTime': json['lead_time'] == null ? undefined : json['lead_time'],
    };
}

export function RawMaterialDetailsToJSON(value?: RawMaterialDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created': DateAttrToJSON(value['created']),
        'updated': DateAttrToJSON(value['updated']),
        'version': value['version'],
        'archived': value['archived'],
        'notes': value['notes'],
        'supplier_id': value['supplierId'],
        'id': value['id'],
        'external_id': value['externalId'],
        'name': value['name'],
        'description': value['description'],
        'categories': value['categories'],
        'uom': value['uom'],
        'supplier_attr': CompanyAttrToJSON(value['supplierAttr']),
        'aggregate_of_id': value['aggregateOfId'],
        'aggregate_of': RawMaterialSummaryToJSON(value['aggregateOf']),
        'aggregate_quantity': value['aggregateQuantity'],
        'prices': PricesAttrToJSON(value['prices']),
        'minimum_quantity': value['minimumQuantity'],
        'attributes': value['attributes'],
        'lead_time': value['leadTime'],
    };
}

