/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RawMaterialInventoryBuckets } from './RawMaterialInventoryBuckets';
import {
    RawMaterialInventoryBucketsFromJSON,
    RawMaterialInventoryBucketsFromJSONTyped,
    RawMaterialInventoryBucketsToJSON,
} from './RawMaterialInventoryBuckets';

/**
 * 
 * @export
 * @interface RawMaterialInventoryItemSummary
 */
export interface RawMaterialInventoryItemSummary {
    /**
     * 
     * @type {string}
     * @memberof RawMaterialInventoryItemSummary
     */
    id?: string;
    /**
     * 
     * @type {RawMaterialInventoryBuckets}
     * @memberof RawMaterialInventoryItemSummary
     */
    buckets?: RawMaterialInventoryBuckets;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialInventoryItemSummary
     */
    rawMaterialId: string;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialInventoryItemSummary
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialInventoryItemSummary
     */
    externalId: string;
}

/**
 * Check if a given object implements the RawMaterialInventoryItemSummary interface.
 */
export function instanceOfRawMaterialInventoryItemSummary(value: object): value is RawMaterialInventoryItemSummary {
    if (!('rawMaterialId' in value) || value['rawMaterialId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('externalId' in value) || value['externalId'] === undefined) return false;
    return true;
}

export function RawMaterialInventoryItemSummaryFromJSON(json: any): RawMaterialInventoryItemSummary {
    return RawMaterialInventoryItemSummaryFromJSONTyped(json, false);
}

export function RawMaterialInventoryItemSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RawMaterialInventoryItemSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'buckets': json['buckets'] == null ? undefined : RawMaterialInventoryBucketsFromJSON(json['buckets']),
        'rawMaterialId': json['raw_material_id'],
        'name': json['name'],
        'externalId': json['external_id'],
    };
}

export function RawMaterialInventoryItemSummaryToJSON(value?: RawMaterialInventoryItemSummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'buckets': RawMaterialInventoryBucketsToJSON(value['buckets']),
        'raw_material_id': value['rawMaterialId'],
        'name': value['name'],
        'external_id': value['externalId'],
    };
}

