/* tslint:disable */
/* eslint-disable */
/**
 * Arke Supply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransportDocumentSummary
 */
export interface TransportDocumentSummary {
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentSummary
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentSummary
     */
    externalId: string;
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentSummary
     */
    status: TransportDocumentSummaryStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof TransportDocumentSummary
     */
    time?: Date;
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentSummary
     */
    supplierId?: string;
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentSummary
     */
    orderInternalId?: string;
    /**
     * 
     * @type {string}
     * @memberof TransportDocumentSummary
     */
    orderId?: string;
}


/**
 * @export
 */
export const TransportDocumentSummaryStatusEnum = {
    Inbound: 'inbound',
    Accepted: 'accepted'
} as const;
export type TransportDocumentSummaryStatusEnum = typeof TransportDocumentSummaryStatusEnum[keyof typeof TransportDocumentSummaryStatusEnum];


/**
 * Check if a given object implements the TransportDocumentSummary interface.
 */
export function instanceOfTransportDocumentSummary(value: object): value is TransportDocumentSummary {
    if (!('externalId' in value) || value['externalId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function TransportDocumentSummaryFromJSON(json: any): TransportDocumentSummary {
    return TransportDocumentSummaryFromJSONTyped(json, false);
}

export function TransportDocumentSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransportDocumentSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'externalId': json['external_id'],
        'status': json['status'],
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
        'supplierId': json['supplier_id'] == null ? undefined : json['supplier_id'],
        'orderInternalId': json['order_internal_id'] == null ? undefined : json['order_internal_id'],
        'orderId': json['order_id'] == null ? undefined : json['order_id'],
    };
}

export function TransportDocumentSummaryToJSON(value?: TransportDocumentSummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'external_id': value['externalId'],
        'status': value['status'],
        'time': value['time'] == null ? undefined : ((value['time']).toISOString()),
        'supplier_id': value['supplierId'],
        'order_internal_id': value['orderInternalId'],
        'order_id': value['orderId'],
    };
}

